### ISSUE TITLE
PDF bug on mobile

### ISSUE THREAD

**Issue by frankmill** [NomarCub/obsidian-copy-url-in-preview#28]
The problem appears as soon as you are back from the PDF editor.

If you tap on the three-dot menu to close the PDF file, the "Opening PDFs externally: line" appears again and again.

The only way to get out is via "Hamburger menu - Command palette - Close current tab" or via the Add new tab button.

Otherwise: the plugin is great; you can edit your PDF file in the PDF editor and immediately have the changes under obsidian. For this my thanks and appreciation !

**Comment by NomarCub** [comment]
@mnaoumov I'd like to ask you again for maintenance on the PDF feature.

**Comment by frankmill** [comment]
It looks like the bug is fixed.

Am I right ?

**Comment by NomarCub** [comment]
It wasn't fixed, no one touched the code since May. I haven't tried to reproduce it in the first place.
Did you have the latest version back then @frankmill? An Obsidian update also could have changed things.

If no one has this bug anymore, and @mnaoumov has no comment on it, I'll close this soon.

**Comment by mnaoumov** [comment]
I'll try to reproduce again later today

**Comment by frankmill** [comment]
The latest Obsidian update was before 21.06.,
after that (on 07.07.) only one of my PDF-editor.

I tested it a few more times, today even more extensively.
It worked without problems.

I think we can sign out #28 as done.

And not to forget:
very, very many thanks for this feature.
Since Obsidian displays PDF, I have been hoping for this.


Especially I do not need to embed annotations, links and so on,
I can edit them later in the PDF editor.
